using System.Collections.ObjectModel;
using NoteManager.App.Models;

namespace NoteManager.App.Services;

public static class SampleDataService
{
    public static ObservableCollection<NoteItem> CreateNotes()
    {
        return
        [
            Note(
                "Northstar Labs — partnership statement.docx",
                "Statement, Northstar Labs, northstarlabs.example",
                "Northstar Labs — partnership statement.docx",
                "108 KB",
                "notebook",
                ThumbnailKind.LegalLetter,
                "PARTNERSHIP STATEMENT",
                "A clear record of our shared direction",
                ["This statement confirms that Northstar Labs and Meridian Works have agreed to collaborate on a new research programme focused on practical automation for distributed teams.",
                 "The partnership combines product design, engineering and operational research. The organisations will share findings, maintain independent governance and publish a summary of the programme after the first review period.",
                 "Both teams believe that calm, dependable software should reduce administrative work while keeping people in control of the decisions that matter.",
                 "The initial programme runs for twelve months and includes quarterly reviews, an accessibility audit and a public demonstration of the resulting prototypes."],
                [".NET", "[Progress]", "1 Ds 356/16", "Northstar Labs", "Statement", "northstarlabs.example"],
                "26.07.2026 15:14"),
            Note(
                "EU_CLEAN_ENERGY_OUTLOOK_2026.pdf",
                "Report, Energy transition, Copenhagen",
                "EU_CLEAN_ENERGY_OUTLOOK_2026.pdf",
                "7.1 MB",
                "Research",
                ThumbnailKind.Globe,
                "CLEAN ENERGY OUTLOOK",
                "European market brief · 2026 edition",
                ["This report summarises emerging clean-energy investment patterns across Europe and highlights practical opportunities for small and mid-sized operators.",
                 "Investment remains strongest in grid flexibility, storage and industrial heat. The next wave of growth is expected to come from smaller regional projects with transparent delivery milestones."],
                ["01/09/2018 - 31/08/2019", "1and1", "Energy", "Europe", "Research", "Sustainability"],
                "18.07.2026 09:40"),
            Note(
                "PKG-482991-shipping-label.pdf",
                "Parcel, Kraków, studio equipment",
                "PKG-482991-shipping-label.pdf",
                "22.2 KB",
                "Purchases",
                ThumbnailKind.ShippingLabel,
                "PARCEL RECORD",
                "Shipment PKG-482991",
                ["Recipient: Northstar Labs, Workshop 4B. Contents: camera support arm and two lighting clamps.",
                 "Carrier scan completed at the regional depot. Estimated delivery is the next business day."],
                ["2Checkout", "70-229", "Equipment", "Parcel", "Purchases", "Shipping"],
                "18.07.2026 08:12"),
            Note(
                "Contract_amendment_2026-07.pdf",
                "Legal, amendment, professional services",
                "Contract_amendment_2026-07.pdf",
                "31.8 KB",
                "Northstar Labs",
                ThumbnailKind.LegalLetter,
                "CONTRACT AMENDMENT",
                "Professional services agreement",
                ["The parties agree to replace the delivery schedule in Appendix B with the milestones described in this amendment.",
                 "All other provisions remain unchanged. This amendment takes effect on the date of the final signature."],
                ["1 DS 734/15", "4 O Clock Interactive sp. z o.o.", "Contracts", "Legal", "Northstar Labs", "Professional services"],
                "17.07.2026 17:35"),
            Note(
                "INV-2026-0715.pdf",
                "Meridian Fuel Services, fleet, invoice",
                "INV-2026-0715.pdf",
                "425 KB",
                "Bills",
                ThumbnailKind.Invoice,
                "INVOICE",
                "Meridian Fuel Services · INV-2026-0715",
                ["Service period: July 2026. Vehicle charging, parking and maintenance supplies are itemised below.",
                 "Payment is due within fourteen days. Please use the invoice number as the transfer reference."],
                ["1 Ds 1383/14", "Bills", "Fleet", "Invoice", "Meridian Fuel Services", "Payments"],
                "17.07.2026 11:58",
                "2 attachments"),
            Note(
                "Q3_operating_budget.pdf",
                "Budget, operations, approved forecast",
                "Q3_operating_budget.pdf",
                "181 KB",
                "Projects",
                ThumbnailKind.Table,
                "Q3 OPERATING BUDGET",
                "Approved working forecast",
                ["The forecast includes travel, research equipment, contractor support and a ten-percent contingency.",
                 "Department leads should record material changes in the review notes before the end-of-month close."],
                ["1 Ds 1464/15", "Finance", "Forecast", "Operations", "Projects", "Q3"],
                "16.07.2026 16:20",
                "2 attachments"),
            Note(
                "Signed_workspace_lease.pdf",
                "Office, lease, signature",
                "Signed_workspace_lease.pdf",
                "3.1 MB",
                "Home",
                ThumbnailKind.SignedLetter,
                "WORKSPACE LEASE",
                "Signed copy · Riverside studio",
                ["This file contains the signed lease for the Riverside studio workspace, including the inventory schedule and access conditions.",
                 "The next annual review is scheduled for January 2027."],
                ["1 Ds 1851/14", "Home", "Lease", "Riverside", "Signed", "Workspace"],
                "15.07.2026 14:45"),
            Note(
                "img20230118_12404076.pdf",
                "Blocki, Manual, Stacja kosmiczna",
                "img20230118_12404076.pdf",
                "16.8 MB",
                "notebook",
                ThumbnailKind.SpacePoster,
                "ORBITAL WORKSHOP",
                "Assembly guide · OW-8307",
                ["A fictional educational construction manual for a modular orbital research station.",
                 "The document contains a cover, illustrated assembly steps and an inventory of sample components."],
                ["Blocki", "Manual", "Stacja kosmiczna"],
                "18.01.2023 12:40"),
            Note(
                "Cafe_receipt_2026-07-13.pdf",
                "Travel, team breakfast, receipt",
                "Cafe_receipt_2026-07-13.pdf",
                "430 KB",
                "Travel",
                ThumbnailKind.Receipt,
                "EXPENSE RECEIPT",
                "Morning Field Café · team breakfast",
                ["Breakfast meeting for four people during the summer planning workshop.",
                 "The receipt total includes local tax and a service charge."],
                ["1 Ds 2089/15", "Cafe", "Receipt", "Travel", "Workshop", "7DayShop"],
                "13.07.2026 10:32"),
            Note(
                "Studio_supplies_2026-07-12.pdf",
                "Purchases, paper, archival sleeves",
                "Studio_supplies_2026-07-12.pdf",
                "1012 KB",
                "Purchases",
                ThumbnailKind.Receipt,
                "PURCHASE RECEIPT",
                "Studio supply order",
                ["Archival folders, document sleeves, printer paper and two label cartridges.",
                 "Order received in full and checked against the delivery note."],
                ["1 Ds 2119 2018", "4Kraft sp. z o.o.", "Paper", "Purchases", "Receipt", "Studio"],
                "12.07.2026 18:04"),
            Note(
                "Research_interviews_round_2.pdf",
                "Research, interview synthesis, workflow",
                "Research_interviews_round_2.pdf",
                "344 KB",
                "Research",
                ThumbnailKind.Report,
                "RESEARCH SYNTHESIS",
                "Round two · workflow interviews",
                ["Participants consistently asked for faster retrieval, stronger visual grouping and fewer modal interruptions.",
                 "The clearest opportunity is a three-pane workspace that keeps navigation, results and the active document visible at the same time."],
                ["1 Ds 2520 2018", "30daytrial", "Interviews", "Research", "Usability", "Workflow"],
                "11.07.2026 13:57"),
            Note(
                "Equipment_service_record.pdf",
                "Operations, maintenance, workstation",
                "Equipment_service_record.pdf",
                "781 KB",
                "Projects",
                ThumbnailKind.Invoice,
                "SERVICE RECORD",
                "Studio workstation maintenance",
                ["The workstation passed thermal, storage and memory diagnostics. Dust filters were replaced and firmware was updated.",
                 "Recommended follow-up: inspect the backup battery during the next quarterly service."],
                ["1 DS 3138 2016", "4Console Michal Olczak", "Equipment", "Maintenance", "Operations", "Service"],
                "10.07.2026 09:18"),
            Note(
                "Annual_review_notes.docx",
                "People, annual review, planning",
                "Annual_review_notes.docx",
                "92 KB",
                "Personal",
                ThumbnailKind.LegalLetter,
                "ANNUAL REVIEW NOTES",
                "Private working document",
                ["The strongest outcomes this year came from simplifying the research process and sharing progress in smaller, more frequent increments.",
                 "Next year’s focus is consistent delivery, mentoring and making the design system easier for every contributor to use."],
                ["1 Ds 3507/15", "8.1", "People", "Personal", "Planning", "Review"],
                "09.07.2026 16:46")
        ];
    }

    private static NoteItem Note(
        string title,
        string subtitle,
        string fileName,
        string size,
        string notebook,
        ThumbnailKind thumbnailKind,
        string documentHeading,
        string documentSubheading,
        string[] paragraphs,
        string[] tags,
        string modifiedAt,
        string attachmentDescription = "1 attachment")
    {
        return new NoteItem
        {
            Title = title,
            Subtitle = subtitle,
            FileName = fileName,
            Size = size,
            Date = modifiedAt[..10],
            Notebook = notebook,
            ThumbnailKind = thumbnailKind,
            DocumentHeading = documentHeading,
            DocumentSubheading = documentSubheading,
            Paragraphs = paragraphs,
            Tags = tags,
            ModifiedAt = modifiedAt,
            AttachmentDescription = attachmentDescription
        };
    }
}
